####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-parser
Description: Open Porous Media Initiative File Parser Library
Version: 2017.10-rc1
Label: 2017.10-rc1
Maintainer: joaho@statoil.com
MaintainerName: Joakim Hove
Url: http://opm-project.org
