####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-parser
Description: Open Porous Media Initiative File Parser Library
Version: 2018.04-pre
Label: 2018.04-pre
Maintainer: joaho@statoil.com
MaintainerName: Joakim Hove
Url: http://opm-project.org
Depends: opm-common
